Initial Commit TinT
oracle-devrel/tint pull request #1
Opened 2021-07-28 02:24 UTC by naikvenu

Initial commit for Tint:
This is a Simple configuration based continuous integration testing tool for terraform developers. This tool performs rich production grade tests on your infrastructure as code. Makes use of opensource terratest framework and sdks and provides a cohesive, user friendly config based approach to write your test cases.

2021-07-28 20:39 UTC, timclegg requested changes
I'm so excited about this!  I raised a couple of very minor suggestions and requests (largely just copyright formatting, with a few other things).  Please take a look and let me know your thoughts?  Thanks so much.

2021-07-28 20:39 UTC, timclegg commented on README.md
> -[![License: UPL](https://img.shields.io/badge/license-UPL-green)](https://img.shields.io/badge/license-UPL-green) [![Quality gate](https://sonarcloud.io/api/project_badges/quality_gate?project=oracle
It would be nice to keep the badges, if ok?  Especially the SonarCloud (gives folks a level of awareness around the quality of the code).

2021-07-28 20:39 UTC, timclegg commented on LICENSE
> -Copyright (c) 2021 Oracle and/or its affiliates.
Not trying to be nit-picky, but could we leave the `LICENSE` file as-is (not change it at all)?

2021-07-28 20:39 UTC, timclegg commented on CONTRIBUTING.md
> +
Can we remove this file for now?  We don't typically include a separate `CONTRIBUTING` file (at least for the time being), but rather have a short paragraph in the README.

2021-07-28 20:39 UTC, timclegg commented on README.md
> -See [LICENSE](LICENSE) for more details.
Can this section be added back into the README (kept as-is)?  That helps to eliminate the need for `CONTRIBUTING` (at least for now) and makes sure that the license is front-and-center.

2021-07-28 20:39 UTC, timclegg commented on commands.go
> +// Copyright (c) 2020 Oracle and/or its affiliates,  All rights reserved.
Very minor, but can the copyright be `Copyright (c) 2021 Oracle and/or its affiliates.`?  This is what's desired for the copyright notice.

2021-07-28 20:39 UTC, timclegg commented on funcs.go
> +//# Copyright (c) 2020 Oracle and/or its affiliates,  All rights reserved.
Please update copyright.

2021-07-28 20:39 UTC, timclegg commented on helpers.go
> +// Copyright (c) 2020 Oracle and/or its affiliates,  All rights reserved.
Update copyright please.

2021-07-28 20:39 UTC, timclegg commented on inputs.go
> +// Copyright (c) 2020 Oracle and/or its affiliates,  All rights reserved.
Update copyright please.

2021-07-28 20:39 UTC, timclegg commented on register.go
> +// Copyright (c) 2020 Oracle and/or its affiliates,  All rights reserved.
Update copyright please.

2021-07-28 20:39 UTC, timclegg commented on sample_yaml_configs/http_sol_config.yaml
> +# Copyright (c) 2020 Oracle and/or its affiliates,  All rights reserved.
Update copyright please.

2021-07-28 20:39 UTC, timclegg commented on sample_yaml_configs/simple_block_volume_config.yaml
> +# Copyright (c) 2020 Oracle and/or its affiliates,  All rights reserved.
Update copyright please.

2021-07-28 20:39 UTC, timclegg commented on sample_yaml_configs/simple_block_volume_config.yaml
> +      availability_domain: "uFjs:US-ASHBURN-AD-1"
Should this be changed to be an env var or retrieve it dynamically (like via a TF data source)?

2021-07-28 20:39 UTC, timclegg commented on tint_test.go
> +// Copyright (c) 2020 Oracle and/or its affiliates,  All rights reserved.
Update copyright please.

2021-07-28 20:39 UTC, timclegg commented on utils.go
> +// Copyright (c) 2020 Oracle and/or its affiliates,  All rights reserved.
Update copyright please.

2021-07-28 20:39 UTC, timclegg commented on variables.go
> +// Copyright (c) 2020 Oracle and/or its affiliates,  All rights reserved.
Update copyright please.

2021-07-28 20:41 UTC, timclegg commented
@naikvenu Please make sure to accept the CLA.  To do this, submit two comments:

1. `I have read the CLA Document and I hereby sign the CLA`
2. `recheck`

This will allow the CLA Assistant check to pass.  Thanks!

2021-08-01 01:34 UTC, naikvenu commented
> **CLA Assistant Lite bot:**
> Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/oracledevrel/devrel-oca-mgmt/blob/main/oca-20210504.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> _**I have read the CLA Document and I hereby sign the CLA**_
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

recheck

2021-08-01 01:51 UTC, naikvenu commented
I have read the CLA Document and I hereby sign the CLA

2021-08-01 01:51 UTC, naikvenu commented
recheck

2023-08-25 06:52 UTC, closed without merging